# Generated by Django 5.0.3 on 2024-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sold_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("0", "Poissons"),
                            ("1", "Fruits-de-mer"),
                            ("2", "Crustacés"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("promotion_status", models.BooleanField(default=False)),
                (
                    "promotion_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "promotion_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("sold_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction",
                    models.CharField(
                        choices=[("0", "Vente"), ("1", "Achat"), ("2", "Retrait")],
                        max_length=20,
                    ),
                ),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("edit_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
