# Generated by Django 5.0.3 on 2024-03-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mytig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="transaction",
            field=models.ManyToManyField(to="mytig.transaction"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ca",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
