<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-18 11:38
=======
# Generated by Django 5.0.3 on 2024-03-19 08:04
>>>>>>> d02b7db101a269d88d2d948efc9e330e1cf51dd7

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('mytig', '0002_product_transaction_transaction_ca'),
=======
    dependencies = [
        ("mytig", "0002_product_transaction_transaction_ca"),
>>>>>>> d02b7db101a269d88d2d948efc9e330e1cf51dd7
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=180)),
=======
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=180)),
>>>>>>> d02b7db101a269d88d2d948efc9e330e1cf51dd7
            ],
        ),
    ]
