# Generated by Django 5.0.3 on 2024-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0002_product_transaction_transaction_ca'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=180)),
            ],
        ),
    ]
