# Generated by Django 5.0.3 on 2024-03-11 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mytig", "0003_coquillageproduct_crustaceproduct_fishproduct"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoquillageProduct",
            new_name="FruitDeMerProduct",
        ),
    ]
