# Generated by Django 5.0.3 on 2024-03-20 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mytig", "0004_transaction_taxes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="edit_date",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="add_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
