# Generated by Django 5.0.3 on 2024-03-24 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mytig", "0005_remove_transaction_edit_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="ca",
            new_name="transaction_price",
        ),
    ]
