from django.core.management.base import BaseCommand, CommandError
from mytig.models import Product


class Command(BaseCommand):
    help = 'Ajoute des données de produits à la base de données'
    
    def handle(self, *args, **kwargs):
        data = [
            {
                "name": "Anchois",
                "purchase_price": 6.99,
                "sold_price": 19.99,
                "quantity": 40,
                "description": "Mediterranean anchovies",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Bar",
                "purchase_price": 20.99,
                "sold_price": 25.99,
                "quantity": 45,
                "description": "Wild sea bass from Brittany",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Bigorneaux",
                "purchase_price": 20.99,
                "sold_price": 28.50,
                "quantity": 45,
                "description": "Bigorneaux fraîchement pêchés sur la côte",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },
            {
                "name": "Crabes",
                "purchase_price": 6.99,
                "sold_price": 15.50,
                "quantity": 20,
                "description": "Crabes frais de l'océan Atlantique",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Crabe royal",
                "purchase_price": 6.99,
                "sold_price": 13.99,
                "quantity": 20,
                "description": "Crabe royal des eaux froides de l'océan Pacifique",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Crevettes tigrées",
                "purchase_price": 14.99,
                "sold_price": 18.50,
                "quantity": 55,
                "description": "Crevettes tigrées géantes de l'Asie du Sud-Est",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Crevettes",
                "purchase_price": 15.99,
                "sold_price": 12.99,
                "quantity": 50,
                "description": "Crevettes fraîches de la côte atlantique",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            }, 
            {
                "name": "Crevettes géantes",
                "purchase_price": 15.99,
                "sold_price": 18.99,
                "quantity": 50,
                "description": "Crevettes géantes fraîches de la mer du Nord",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
             {
                "name": "Crabe des neiges",
                "purchase_price": 18.99,
                "sold_price": 28.50,
                "quantity": 30,
                "description": "Crabe des neiges frais pêché dans les eaux froides",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Crevettes roses",
                "purchase_price": 11.99,
                "sold_price": 15.99,
                "quantity": 35,
                "description": "Crevettes roses fraîches de Méditerranée",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Coquilles Saint-Jacques",
                "purchase_price": 18.99,
                "sold_price": 29.50,
                "quantity": 30,
                "description": "Délicieuses coquilles Saint-Jacques fraîches",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },
            {
                "name": "Dorade",
                "purchase_price": 12.99,
                "sold_price": 15.50,
                "quantity": 25,
                "description": "Mediterranean sea bream",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Espadon",
                "purchase_price": 17.99,
                "sold_price": 26.50,
                "quantity": 15,
                "description": "Fresh swordfish",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Écrevisses",
                "purchase_price": 12.99,
                "sold_price": 15.99,
                "quantity": 25,
                "description": "Écrevisses fraîches de rivière",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },
            {
                "name": "Homards",
                "purchase_price": 14.99,
                "sold_price": 23.50,
                "quantity": 55,
                "description": "Homards fraîchement pêchés dans les eaux côtières",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Homard breton",
                "purchase_price": 10.49,
                "sold_price": 8.99,
                "quantity": 40,
                "description": "Homard breton de qualité supérieure",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Homard européen",
                "purchase_price": 17.99,
                "sold_price": 0.00,
                "quantity": 15,
                "description": "Homard européen de la Manche",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Huîtres",
                "purchase_price": 10.49,
                "sold_price": 8.99,
                "quantity": 40,
                "description": "Huîtres spéciales de Bretagne",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },
            {
                "name": "Langoustines",
                "purchase_price": 12.99,
                "sold_price": 0.00,
                "quantity": 25,
                "description": "Langoustines fraîches pêchées au large",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },
            {
                "name": "Maquereau",
                "purchase_price": 7.99,
                "sold_price":12.24,
                "quantity": 60,
                "description": "Fresh mackerel caught off the coast",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Morue",
                "purchase_price": 11.99,
                "sold_price": 15.50,
                "quantity": 35,
                "description": "Atlantic cod for traditional fish and chips",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            }, 
            {
                "name": "Moules",
                "purchase_price": 7.99,
                "sold_price": 13.99,
                "quantity": 60,
                "description": "Moules fraîches de la baie de Mont-Saint-Michel",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },   
            {
                "name": "Palourdes",
                "purchase_price": 11.99,
                "sold_price": 23.50,
                "quantity": 35,
                "description": "Palourdes fraîches de Normandie",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },
            {
                "name": "Saint-Pierre",
                "purchase_price": 17.99,
                "sold_price": 0.00,
                "quantity": 15,
                "description": "Saint-Pierre sauvage de la Manche",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '1',
            },        
            {
                "name": "Saumon",
                "purchase_price": 15.99,
                "sold_price": 12.99,
                "quantity": 50,
                "description": "Fresh Atlantic salmon fillets",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Sole",
                "purchase_price": 18.99,
                "sold_price": 25.50,
                "quantity": 30,
                "description": "Dover sole from the English Channel",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Thon",
                "purchase_price": 14.99,
                "sold_price": 19.99,
                "quantity": 55,
                "description": "Yellowfin tuna steaks",
                "availability": True,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            },
            {
                "name": "Tourteau",
                "purchase_price": 20.99,
                "sold_price": 0.00,
                "quantity": 45,
                "description": "Tourteau fraîchement pêché sur les côtes",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '2',
            },
            {
                "name": "Truite",
                "purchase_price": 10.49,
                "sold_price": 13.99,
                "quantity": 40,
                "description": "Rainbow trout from local rivers",
                "availability": False,
                "promotion_status": False,
                "promotion_price": 0.00,
                "promotion_percent": 0.00,
                "sold_number": 0,
                "category": '0',
            }, 
            
        ]
        
        for product_data in data:       
            product = Product.objects.create(**product_data)
            self.stdout.write(self.style.SUCCESS(f"Produit '{product.name}' ajouté à la base de données."))
        self.stdout.write(self.style.SUCCESS("Tous les produits ont été ajoutés avec succès."))


              